services:
  - type: web
    name: neocart
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
